### PR TITLE
minor fixes prior to release

### PR DESCRIPTION
**Pull request by johannct**
…/ dir from linguist

## Change Description

- [x] My PR includes a link to the issue that I am addressing

## Code Quality
- [x] I have read the Contribution Guide
- [x] My code follows the code style of this project
- [x] My code builds (or compiles) cleanly without any errors or warnings
- [x] My code contains relevant comments and necessary documentation

### Bug Fix Checklist
- [ ] My fix includes a new test that breaks as a result of the bug (if possible)
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### New Feature Checklist
- [ ] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### Documentation Change Checklist
- [ ] Any updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)

### Build/CI Change Checklist
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the README to reflect this
- [ ] If this is a new CI setup, I have added the associated badge to the README

### Other Change Checklist
- [ ] Any new or updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover any changes
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### CODE REVIEW

**Comment by johannct** [comment]
Solving #186

**Comment by raphaelshirley** [comment]
Looks like removing setup.py breaks the build and unit tests?

**Comment by johannct** [comment]
> Looks like removing setup.py breaks the build and unit tests?

I do not see that it is used anywhere....

**Comment by raphaelshirley** [comment]
Isn't it still required for all the c++ build stuff?

https://stackoverflow.com/questions/71193095/questions-on-pyproject-toml-vs-setup-py#:~:text=py%20with%20pyproject.-,toml.,but%20poetry%20and%20flit%20do.

**Comment by johannct** [comment]
yes... clearly cmake is not known to the toml file.... @drewoldag ?

**Comment by johannct** [comment]
I removed my name from setup.py, which I put back in the release : it does look like we need it on top of myproject.toml, @drewoldag

**Comment by drewoldag** [comment]
@johannct I would assume that since you've removed your name from setup.py, that would fix the issue you noted on PyPI with a mismatch between owner name and email address. And yes, looking at it again, it does make sense that what is in setup.py would still be required for the build process.

**Comment by johannct** [comment]
@raphaelshirley @olivierilbert this is ready to merge

**Comment by johannct** [comment]
@raphaelshirley @olivierilbert The Home info on pypi is also taken from the setup.py file and currently points to the LAM gitlab repo. What choice of home page do we want to make : 1/ github source repo; 2/ readthedoc entry page; 3/ a custom page hoster at LAM?
I would be in favor of 2.

**Review by raphaelshirley — APPROVED** [review]
LGTM

**Comment by raphaelshirley** [comment]
Option 2 Sounds like the best option to me too.

**Pull request merged**
