### PR TITLE
Fix broken build

### LINKED ISSUE #159: Fix failing smoke tests
The smoke tests are failing:

https://github.com/lephare-photoz/lephare/actions/runs/9560338829

FAILED tests/lephare/test_filter.py::test_filtersvc - ValueError: resize only works on single-segment arrays
FAILED tests/lephare/test_filter.py::test_flt_plot_filter_curve - ValueError: resize only works on single-segment arrays
FAILED tests/lephare/test_sed.py::test_sed_fromfile - ValueError: resize only works on single-segment arrays
FAILED tests/lephare/test_sed.py::test_sed_readwrite - ValueError: resize only works on single-segment arrays

We believ this may be due to a numpy update. We therefore consider temporarily pinning numpy to the previous version and/or updating numpy to be numpy 2.0 compatible.

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

### PR DESCRIPTION
**Pull request by raphaelshirley**
The overnight smoke tests started failing which we believe may be due to a numpy upgrade

Closes #159 

In this PR I experiment with some changes to the pyproject.toml to upgrade numpy.

It seems to be the lephare.SED class that is causing issues which is bound with pybind so perhaps it is clashing with numpy.

Before submitting this PR, please ensure that your input and responses are entered in the designated space provided 
- [ ] My PR includes a link to the issue that I am addressing

## Code Quality
- [ ] I have read the Contribution Guide
- [ ] My code follows the code style of this project
- [x] My code builds (or compiles) cleanly without any errors or warnings
- [x] My code contains relevant comments and necessary documentation

### Bug Fix Checklist
- [ ] My fix includes a new test that breaks as a result of the bug (if possible)
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### New Feature Checklist
- [ ] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### Documentation Change Checklist
- [ ] Any updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)

### Build/CI Change Checklist
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the README to reflect this
- [ ] If this is a new CI setup, I have added the associated badge to the README

### Other Change Checklist
- [ ] Any new or updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover any changes
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### CODE REVIEW

**Comment by raphaelshirley** [comment]
Adding the ruff line to the pyproject.toml appears to have no impact on the ruff run.

**Comment by raphaelshirley** [comment]
Ok well it looks like the numpy<2 in the pyproject.toml gets the build working.

**Comment by johannct** [comment]
we may need to run this through rail developers. We will not be able to to have numpy<2 if rail moves ahead with numpy 2

**Comment by raphaelshirley** [comment]
I think it may be coming from the data bindings for SED and flt e.g.:

```
      .def("data", [](const SED &f) {
        int N = f.lamb_flux.size();
        py::array_t<double> result = py::array_t<double>(N * 2);
        py::buffer_info buf = result.request();
        double *ptr = (double *)buf.ptr;
        for (size_t i = 0; i < N; i++) {
          ptr[i] = f.lamb_flux[i].lamb;
          ptr[N + i] = f.lamb_flux[i].val;
        }
        result.resize({N, N});
        return result;
      });
```

from 

https://github.com/lephare-photoz/lephare/blob/main/src/lib/_bindings.cc#L174

and 

https://github.com/lephare-photoz/lephare/blob/main/src/lib/_bindings.cc#L127

Can numpy.ascontiguousarray help?

https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html

**Comment by raphaelshirley** [comment]
Screenshot 2024-06-18 at 17 20 03

from chat gpt. Can we simply remove the resize

**Comment by raphaelshirley** [comment]
Or else move the resizing to the Python and perform it on a copy?

**Comment by johannct** [comment]
I had copied this code from some place, so let's try chatGPT solution. Can you test it?

**Comment by raphaelshirley** [comment]
Yep I'll test...

**Comment by raphaelshirley** [comment]
Nope it breaks the test_sed locally and on github.

**Comment by raphaelshirley** [comment]
I think the new pybind code is now doing the same as before given the tests are now passing. the original ChatGPT solution failed I think because the arrays were transposed. I also removed plt.show from the _spec.py and changed the yvals in test_pdf to prevent taking logs of zero in order to remove warnings.

**Review by johannct — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
