### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raphaelshirley**
Make git cloning explicit as recommended by @olivierilbert

### CODE REVIEW

**Comment by raphaelshirley** [comment]
Hi @johannct Can we use this PR to finalise the readme?

**Comment by johannct** [comment]
> Hi @johannct Can we use this PR to finalise the readme?
Yes, but based on agreement on the RFC first : #166

**Comment by johannct** [comment]
Please review, I think I captured more or less everything we mentioned we wanted in the README

**Comment by raphaelshirley** [comment]
Looks good to merge I think. Needs to be reviewed by someone else as I made the original PR.

**Comment by olivierilbert** [comment]
Hello @johannct and @raphaelshirley 
I modified the README. Let me know if it is fine.

**Review by johannct — APPROVED** [review]
LGTM

**Pull request merged**
