### PR TITLE
Added 313 to PyPi publish

### LINKED ISSUE #215: Extend Python version coverage
It seems Python 3.13 is increasingly used. We may need to add this version to 

github/workflows/publish-to-pypi.yml
.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml

Should we also extend to 3.14?

https://devguide.python.org/versions/

Astropy is currently only building to 3.13:

https://pypi.org/project/astropy/#files

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [x] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [x] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

### PR DESCRIPTION
**Pull request by raphaelshirley**
Closes #215 

We need to extend testing to match built versions.

## Code Quality
- [x] I have read the Contribution Guide
- [x] My code follows the code style of this project
- [ ] My code builds (or compiles) cleanly without any errors or warnings
- [x] My code contains relevant comments and necessary documentation

### Bug Fix Checklist
- [ ] My fix includes a new test that breaks as a result of the bug (if possible)
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### New Feature Checklist
- [ ] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### Documentation Change Checklist
- [ ] Any updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)

### Build/CI Change Checklist
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the README to reflect this
- [ ] If this is a new CI setup, I have added the associated badge to the README

### Other Change Checklist
- [ ] Any new or updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover any changes
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### CODE REVIEW

**Comment by raphaelshirley** [comment]
Strange the c++ code coverage is now failing on the 3.10 test.

**Comment by raphaelshirley** [comment]
@johannct What do you think? It is passing all the tests after I changed one data retrieval test to acomodate Python 3.13. I also added a line to the lcov command to fix the issue that appeared out of nowhere. Finally I added recursive to the sdist commands but I think we'll have to publish to PyPI tp see if that has worked.

**Review by johannct — APPROVED** [review]
ok let's give it a spin. We should try to be a bit more verbose in the commit comments, so that the review is easier. Here I do not know what exactly was the test failure mode with py3.13 nor what the new lcov options are supposed to mean. Comments are a way to share information and gained knowledge.

**Comment by johannct** [comment]
please merge and publish as 0.12. But we wont be able to test as now binaries are going to be available with py3.13

**Comment by raphaelshirley** [comment]
You can force from source https://pip.pypa.io/en/latest/cli/pip_install/#install-no-binary

**Comment by raphaelshirley** [comment]
I will add more commit comments going forward

**Comment by johannct** [comment]
> You can force from source https://pip.pypa.io/en/latest/cli/pip_install/#install-no-binary

oh right, good catch

**Comment by raphaelshirley** [comment]
@johan I need an approving review to merge.

**Comment by raphaelshirley** [comment]
Ah you already did...

**Pull request merged**
