### PR TITLE
Exposing python scripts for command line use

### PR DESCRIPTION
**Pull request by drewoldag**
This PR exposes 4 python scripts that can be executed from the command line in the same way that the compiled C code was executed previously. 

For testing I used https://gitlab.lam.fr/Galaxies/LEPHARE/-/blob/master/tests/test_suite.sh?ref_type=heads and copied the commands over as identically as possibe. All of the code seems to be running as expected with the exception of zphota.

The commands that I am running to test are the following: 
```
(lephare) drew@ lephare % export LEPHAREDIR=/Users/drew/Library/Caches/lephare/data
(lephare) drew@ lephare % export LEPHAREWORK=/Users/drew/Library/Caches/lephare/work

(lephare) drew@ lephare % filter -c $LEPHAREDIR/examples/COSMOS.para

(lephare) drew@ lephare % sedtolib -c $LEPHAREDIR/examples/COSMOS.para -t S --STAR_SED $LEPHAREDIR/sed/STAR/STAR_MOD_ALL.list --LIB_ASCII YES

(lephare) drew@ lephare % maggal -c $LEPHAREDIR/examples/COSMOS.para -t S --LIB_ASCII YES --STAR_LIB_OUT ALLSTAR_COSMOS  

(lephare) drew@ lephare % sedtolib -c $LEPHAREDIR/examples/COSMOS.para -t Q --QSO_SED $LEPHAREDIR/sed/QSO/SALVATO09/AGN_MOD.list  

(lephare) drew@ lephare % maggal -c $LEPHAREDIR/examples/COSMOS.para -t Q --MOD_EXTINC 0,1000 --EB_V 0.,0.1,0.2,0.3 --EXTINC_LAW SB_calzetti.dat --LIB_ASCII NO --Z_STEP 0.04,0,6 --LIB_ASCII YES

(lephare) drew@ lephare % sedtolib -c $LEPHAREDIR/examples/COSMOS.para -t G --GAL_SED $LEPHAREDIR/examples/COSMOS_MOD.list --GAL_LIB LIB_VISTA 

(lephare) drew@ lephare % maggal -c $LEPHAREDIR/examples/COSMOS.para -t G --GAL_LIB_IN LIB_VISTA --GAL_LIB_OUT VISTA_COSMOS_FREE --MOD_EXTINC 18,26,26,33,26,33,26,33  --EXTINC_LAW SMC_prevot.dat,SB_calzetti.dat,SB_calzetti_bump1.dat,SB_calzetti_bump2.dat  --EM_LINES EMP_UV  --EM_DISPERSION 0.5,0.75,1.,1.5,2. --Z_STEP 0.04,0,6 --LIB_ASCII YES
```

All of which seem to be running as expected. I'm finding new output sent to my work directory and the files sizes are non-zero. 

When I run zphota though, I get segmentation fault errors. For reference, this is the zphota command that I am running: 
```
(lephare) drew@ lephare % zphota -c $LEPHAREDIR/examples/COSMOS.para --CAT_IN $LEPHAREDIR/examples/COSMOS.in --ZPHOTLIB VISTA_COSMOS_FREE,ALLSTAR_COSMOS,QSO_COSMOS  --ADD_EMLINES 0,100 --AUTO_ADAPT YES --Z_STEP 0.04,0,6 --CAT_LINES 1,100 --SPEC_OUT YES --PARA_OUT $LEPHAREDIR/examples/output.para --VERBOSE NO --ZFIX NO --PDZ_OUT $LEPHAREWORK/zphota/
```
And I get the following seg fault error message: `zsh: segmentation fault  zphota -c $LEPHAREDIR/examples/COSMOS.para --CAT_IN  --ZPHOTLIB  --ADD_EMLINE`

If I run the C++ executable with the same parameters, it _seems_ to run as expected. All of the output files that were produced by the version of lephare that Johann demonstrated at the beginning of the incubator are still produced and are have a non-zero size. They are placed in the wrong directory which is odd - they are ending up in the top level directory, which is neither $LEPHAREWORK nor $LEPHAREDIR.

### CODE REVIEW

**Review by johannct — APPROVED** [review]
I fixed the problem with zphota in a commit.
Should we take this opportunity to add test_suite.sh, properly reworked with the python calls, and the 2 scripts spec.py and figuresLPZ.py in the examples directory?

**Comment by drewoldag** [comment]
I think we already have the two python scripts `spec.py` and `figuresLPZ.py` in the examples directory, so we're good on that front. Unless of course, they need to be modified in some way...

Would you want to include the test_suite.sh as a unit test that is executed along with the rest of the pytests? Or were you thinking of just including it in the examples directory for users to experiment with locally? Either way is fine, I would just need some time to research how to incorporate running a .sh file into the rest of the test suite.

**Comment by johannct** [comment]
No, I thought just in the examples dir. Running automatically could be a good thing, but only on a push to master. It does not have to be the same test script being run in the workflow, it could just be a dedicated workflow that does the same sequence of calls, and allow for retrieval of the 3 main output files.

**Comment by drewoldag** [comment]
@johannct I've been chatting with Raphael about the path forward here. I would like to go ahead and merge this PR, and I'll open a separate issue for the test_suite.sh work. To provide a bit more detail, I would like to expand the test_suite.sh script a little bit so that it can grab the COSMOS.in file from the lephare-data directory and try to reduce the use of explicit env vars as much as possible.

The short term goal would be to have a single script that a user could run immediately after cloning the source code. And as a second goal would be to make sure that we can run the script as an integration test as needed.

**Pull request merged**
